"""ASHA over ``n``: screen wide and cheap, spend resolution only on survivors.

Two constraints set this design, and both are measured.

**The evaluation is noisy.** To separate a ρ=0.25 candidate from a ρ=0.15 one
the gap is 0.074 and the noise is:

====== ====== ======
n      noise  usable
====== ====== ======
35     0.231  no
250    0.103  no
1,000  0.046  no
2,000  0.033  yes
====== ====== ======

So rung 1 (n=300) and rung 2 (n=1,000) buy **direction only**. No promotion
decision is made below rung 3, and :func:`promotable` refuses to hand one back.

**Rungs must nest.** An arm promoted from 300 to 1,000 should pay for 700 new
events, not 1,000. :func:`rung_events` therefore returns a deterministic prefix
of one fixed ordering, so every rung is a subset of the next and every arm is
scored on identical events at identical rungs — which is what keeps the
comparison paired and the quarter difficulty out of it.

That ordering puts the 2,100 events already generated by ``arms.py`` first, so
rungs 1–3 come out of cache for any arm that has run before and cost nothing to
re-score.

The promotion rule is ASHA's, not synchronous successive halving's: an arm is
promotable as soon as it ranks in the top ``1/η`` of the arms that have finished
its rung, whether or not the rest have. Nothing waits for a straggler.
"""

from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import asdict, dataclass, field
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import harness  # noqa: E402
import reads  # noqa: E402

STATE = ROOT / "runs" / "schedule.json"

#: Total events per rung, summed across dev quarters. Rung 3 is the first that
#: can carry a promotion decision; anything below it is a screen.
RUNGS = (300, 1000, 2000)

#: The rung at or above which a promotion decision is allowed. Hard constraint 1
#: in BUILD_LOOP.md, enforced here rather than remembered.
SELECTION_RUNG = 2  # zero-indexed -> RUNGS[2] == 2000

#: Successive-halving reduction factor. Top 1/3 of each rung survives.
ETA = 3

#: Minimum arms finished at a rung before any promotion is allowed. Below this
#: "top 1/3 of what has finished" is one arm out of two, which is not a screen.
MIN_COHORT = 3

#: Metered spend ceiling, USD. OpenRouter/OpenAI only — Claude Code is on a Max
#: plan, so building and analysing is unmetered and only scoring runs count.
#: BUILD_LOOP.md: hold at 25 cumulative and ask before exceeding.
SPEND_CAP = 25.0

#: Spend that happened before this ledger existed, as of 2026-08-17.
SPEND_PRIOR = 11.81


# --------------------------------------------------------------------------
# The nested event ordering
# --------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _ordering() -> tuple[tuple[str, str], ...]:
    """``(quarter, event_id)`` in the fixed order rungs are prefixes of.

    Three properties, each load-bearing:

    * **already-generated events first.** The 700-per-quarter screening sample
      ``arms.py`` used is put at the head, so a re-scored arm pays nothing for
      rungs 1–3.
    * **round-robin across quarters.** Any prefix is balanced, so rung 1 is not
      accidentally three-quarters of one quarter — which would make its
      difficulty, not the arm, the thing being measured.
    * **hashed within a quarter**, not sorted by ``event_id`` and strided.
      Striding a sorted list changes membership when the stride changes, and
      nesting is the property this ordering exists to provide.
    """
    screened = {e["event_id"] for e in reads.screen_events(reads.SCREEN_PER_QUARTER)}
    per_quarter: dict[str, list[str]] = {}
    for quarter in harness.DEV_QUARTERS:
        ids = [e["event_id"] for e in harness.events_for(quarter)]
        per_quarter[quarter] = sorted(
            ids,
            key=lambda i: (i not in screened, hashlib.sha256(i.encode()).hexdigest()),
        )
    order: list[tuple[str, str]] = []
    for i in range(max(len(v) for v in per_quarter.values())):
        for quarter in harness.DEV_QUARTERS:
            if i < len(per_quarter[quarter]):
                order.append((quarter, per_quarter[quarter][i]))
    return tuple(order)


def universe_size() -> int:
    return len(_ordering())


def rung_events(n: int | None = None) -> dict[str, list[dict]]:
    """The first ``n`` events of the fixed ordering, grouped by quarter.

    ``None`` means every dev event — the rung a final promotion decision runs
    on when a candidate has already earned it.
    """
    order = _ordering()
    take = order if n is None else order[:n]
    wanted: dict[str, set[str]] = {}
    for quarter, event_id in take:
        wanted.setdefault(quarter, set()).add(event_id)
    out: dict[str, list[dict]] = {}
    for quarter, ids in wanted.items():
        out[quarter] = [e for e in harness.events_for(quarter) if e["event_id"] in ids]
    return out


def rung_size(rung: int) -> int | None:
    return RUNGS[rung] if rung < len(RUNGS) else None


def confirmation_events() -> dict[str, list[dict]]:
    """Dev events **no rung ever touches** — the partition selection cannot see.

    This is the answer to the loop's own central problem, and it is the answer
    the post-selection-inference literature gives: to get an unbiased value for
    the best of ``K`` noisy candidates, select on one sample and estimate on
    another. Every other correction — deflated fitness, best-of-K multipliers,
    effective-``K`` adjustments — is an *estimate* of the bias under assumptions
    about independence and normality that our arms (mutually correlated at
    0.824) do not satisfy. A split needs no assumptions at all.

    It is nearly free here. The rungs occupy the first 2,000 events of a 6,144
    event ordering, so **4,144 dev events are already unused**, disjoint by
    construction, and cost nothing to score for any arm whose column is cached.

    Distinct from :data:`HOLDOUT` (2026Q3), which is sealed and spent once on
    the final model. This is the intermediate check the loop runs every
    generation: the gap between an arm's selection-set number and its
    confirmation number *is* the measured selection bias, rather than a
    formula's guess at it.
    """
    order = _ordering()
    tail = order[RUNGS[-1]:]
    wanted: dict[str, set[str]] = {}
    for quarter, event_id in tail:
        wanted.setdefault(quarter, set()).add(event_id)
    return {
        quarter: [e for e in harness.events_for(quarter) if e["event_id"] in ids]
        for quarter, ids in wanted.items()
    }


def new_events(arm_rung: int | None, target_rung: int) -> dict[str, list[dict]]:
    """Events at ``target_rung`` that were not already in ``arm_rung``.

    What :meth:`Arm.ensure` is asked to generate. Promotion pays the difference,
    not the total.
    """
    target = rung_events(rung_size(target_rung))
    if arm_rung is None:
        return target
    already = rung_events(rung_size(arm_rung))
    out = {}
    for quarter, events in target.items():
        seen = {e["event_id"] for e in already.get(quarter, [])}
        out[quarter] = [e for e in events if e["event_id"] not in seen]
    return out


# --------------------------------------------------------------------------
# Metered spend
# --------------------------------------------------------------------------

#: Directories whose JSONL columns carry ``prompt_tokens`` / ``completion_tokens``.
SPEND_DIRS = ("arms", "reads", "frontier")


def _model_from_filename(path: Path) -> str:
    """``rulebook__google_gemini-2.5-flash-lite.jsonl`` -> the OpenRouter id."""
    stem = path.stem
    tail = stem.split("__")[-1]
    return tail.replace("_", "/", 1) if "_" in tail else tail


def spent_usd() -> float:
    """Everything the token ledgers on disk say we have spent, plus the prior.

    Reconstructed from the columns rather than tracked in a counter, because a
    counter drifts and the columns are the artefact that actually cost money.
    """
    import frontier

    total = 0.0
    for directory in SPEND_DIRS:
        for path in (ROOT / "data" / directory).glob("*.jsonl"):
            price_in, price_out = frontier.PRICES.get(_model_from_filename(path), (0.10, 0.40))
            tin = tout = 0
            for line in path.open():
                if not line.strip():
                    continue
                row = json.loads(line)
                tin += row.get("prompt_tokens") or 0
                tout += row.get("completion_tokens") or 0
            total += tin * price_in / 1e6 + tout * price_out / 1e6
    return total


def budget_remaining() -> float:
    return SPEND_CAP - max(spent_usd(), SPEND_PRIOR)


# --------------------------------------------------------------------------
# The schedule itself
# --------------------------------------------------------------------------


@dataclass
class State:
    """Which rung each arm has reached, and what it scored there.

    Persisted after every step. An interrupted loop resumes at the rung it
    reached — the LLM columns are on disk anyway, so a restart that forgot the
    schedule would re-score for free but re-decide from scratch.
    """

    rung: dict[str, int] = field(default_factory=dict)
    fitness: dict[str, dict[str, float]] = field(default_factory=dict)
    dropped: dict[str, str] = field(default_factory=dict)

    def save(self, path: Path = STATE) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(asdict(self), indent=2))

    @classmethod
    def load(cls, path: Path = STATE) -> State:
        if not path.exists():
            return cls()
        return cls(**json.loads(path.read_text()))

    def record(self, arm: str, rung: int, fitness: float, standalone: float) -> None:
        self.rung[arm] = rung
        self.fitness.setdefault(str(rung), {})[arm] = fitness
        self.fitness.setdefault(f"{rung}_standalone", {})[arm] = standalone

    def drop(self, arm: str, reason: str) -> None:
        self.dropped[arm] = reason


def promotable(
    state: State,
    arm: str,
    rung: int,
    *,
    holds_cell: bool = True,
    costed: bool = True,
) -> tuple[bool, str]:
    """Two gates, and they answer different questions.

    **Quality-diversity gate — does the arm still hold an archive cell?** This
    is the one that keeps the loop from converging on redundancy. Fifteen read
    columns all land in the same ``(ρ_b band, family, tier)`` cell, so at most
    one of them survives it however well they score standalone. That is the
    six-models-one-arm result made operational: a family cannot buy promotion
    slots with arm count.

    **Budget gate — is the arm in the top ``1/η`` of this rung's cohort?**
    Successive halving exists to allocate *spend*. An arm that costs nothing to
    take deeper consumes no budget, so applying the bar to it would discard
    information for free. Only costed arms face it.

    Returns ``(False, reason)`` rather than raising: a silent drop is how "we
    tried forty things" quietly becomes "we found one thing".
    """
    cohort = state.fitness.get(str(rung), {})
    if arm not in cohort:
        return False, f"not scored at rung {rung}"
    # Both gates exist to ration *spend*. A free arm consumes none, so dropping
    # it discards information for nothing — and at rung 0 the noise is 0.231
    # against candidate gaps of ~0.07, so a cell contest decided there is a coin
    # flip. Free arms ride to the decision rung and are judged where the
    # measurement can carry a judgement.
    if not costed:
        return True, "costs nothing to take deeper"
    if not holds_cell:
        return False, f"lost its archive cell at rung {rung} — a redundant duplicate of a better arm"
    if len(cohort) < MIN_COHORT:
        return False, f"only {len(cohort)} arms finished rung {rung}; need {MIN_COHORT}"
    ranked = sorted(cohort, key=lambda a: cohort[a], reverse=True)
    keep = max(1, len(ranked) // ETA)
    position = ranked.index(arm) + 1
    if position <= keep:
        return True, f"rank {position}/{len(ranked)} at rung {rung}, top {keep} promote"
    return False, f"rank {position}/{len(ranked)} at rung {rung}, only top {keep} promote"


def can_decide(rung: int) -> bool:
    """No promotion decision below n=2,000. Hard constraint 1."""
    return rung >= SELECTION_RUNG


if __name__ == "__main__":
    order = _ordering()
    print(f"universe {len(order)} dev events")
    for i, n in enumerate(RUNGS):
        events = rung_events(n)
        counts = {q: len(v) for q, v in sorted(events.items())}
        print(f"  rung {i}: n={n:<5} {counts}  decision-grade={can_decide(i)}")

    # Nesting is the property everything else rests on. Assert it rather than
    # trusting that a hash order stayed stable.
    small = {e["event_id"] for v in rung_events(RUNGS[0]).values() for e in v}
    big = {e["event_id"] for v in rung_events(RUNGS[-1]).values() for e in v}
    assert small <= big, "rungs must nest or promotion pays twice"
    print(f"\nrungs nest: {len(small)} in {len(big)}")

    screened = {e["event_id"] for e in reads.screen_events(reads.SCREEN_PER_QUARTER)}
    print(f"rung {RUNGS[-1]} inside the already-generated screening set: "
          f"{len(big & screened)}/{len(big)}")

    print(f"\nmetered spend so far ${spent_usd():.2f}  "
          f"(prior floor ${SPEND_PRIOR:.2f}, cap ${SPEND_CAP:.2f}, "
          f"remaining ${budget_remaining():.2f})")
